# Generated by Django 5.1.1 on 2024-09-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_update_at_user_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
